tap "github/gh"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "ack"
brew "antigen"
brew "aria2"
brew "coreutils"
brew "asdf"
brew "bat"
brew "node"
brew "bitwarden-cli"
brew "boost"
brew "cabal-install"
brew "glib"
brew "cmake"
brew "cookiecutter"
brew "cowsay"
brew "curl"
brew "deno"
brew "gmp"
brew "harfbuzz"
brew "ffmpeg"
brew "fortune"
brew "fzf"
brew "gcc"
brew "gh"
brew "git"
brew "git-flow"
brew "gnu-sed"
brew "go"
brew "haskell-stack"
brew "htop"
brew "imagemagick"
brew "jq"
brew "mas"
brew "md5sha1sum", link: false
brew "mosh"
brew "ncdu"
brew "neofetch"
brew "nvm"
brew "openblas"
brew "perl"
brew "pipx"
brew "ponysay"
brew "pyenv"
brew "qpdf"
brew "ruby"
brew "scc"
brew "speedtest-cli"
brew "syncthing", link: false
brew "thefuck"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "yadm"
brew "yarn"
brew "youtube-dl"
brew "heroku/brew/heroku"
cask "alacritty"
cask "balenaetcher"
cask "bitwarden"
cask "brave-browser"
cask "calibre"
cask "dash"
cask "detexify"
cask "discord"
cask "docker"
cask "dozer"
cask "font-jetbrains-mono"
cask "google-backup-and-sync"
cask "grammarly"
cask "haptickey"
cask "iterm2"
cask "jetbrains-space"
cask "jetbrains-toolbox"
cask "keka"
cask "keyboardcleantool"
cask "mactex"
cask "meetingbar"
cask "miniconda"
cask "notion"
cask "obs"
cask "onyx"
cask "openinterminal"
cask "openvpn-connect"
cask "pock"
cask "protonvpn"
cask "quitter"
cask "spotify"
cask "steam"
cask "syncthing"
cask "teamviewer"
cask "tor-browser"
cask "transmission"
cask "virtualbox"
cask "vlc"
cask "zoomus"
mas "1440", id: 1483764819
mas "AdGuard for Safari", id: 1440147259
mas "Amphetamine", id: 937984704
mas "Fantastical", id: 975937182
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "MindNode", id: 1289197285
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "Shazam", id: 897118787
mas "Studies", id: 1071676469
mas "Telegram", id: 747648890
mas "Tweetbot", id: 1384080005
