tap "github/gh"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mtslzr/marmaduke-chromium"
brew "ack"
brew "ant"
brew "antigen"
brew "aria2"
brew "asciinema"
brew "coreutils", link: false
brew "asdf"
brew "bat"
brew "binutils"
brew "boost"
brew "glib"
brew "cmake"
brew "cookiecutter"
brew "cowsay"
brew "curl"
brew "deno"
brew "docker-compose", link: false
brew "gmp"
brew "gnutls"
brew "harfbuzz"
brew "ffmpeg"
brew "fortune"
brew "fzf"
brew "gcc"
brew "gdb"
brew "gh"
brew "git"
brew "git-flow"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "gradle"
brew "node"
brew "grunt-cli"
brew "htop"
brew "httpie"
brew "hugo"
brew "imagemagick"
brew "jq"
brew "kubernetes-cli"
brew "mas"
brew "maven"
brew "md5sha1sum", link: false
brew "minikube"
brew "mosh"
brew "ncdu"
brew "neofetch"
brew "nuget"
brew "qpdf"
brew "ocrmypdf"
brew "openblas"
brew "pandoc"
brew "perl"
brew "pipx"
brew "ponysay"
brew "pyenv"
brew "python@3.7"
brew "python@3.8"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "ruby"
brew "scc"
brew "speedtest-cli"
brew "syncthing", link: false
brew "thefuck"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "yadm"
brew "yarn"
brew "youtube-dl"
brew "zenith"
cask "1password-cli"
cask "alacritty"
cask "balenaetcher"
cask "blackhole-2ch"
cask "brave-browser"
cask "calibre"
cask "cleanshot"
cask "dash"
cask "detexify"
cask "discord"
cask "docker"
cask "dozer"
cask "eul"
cask "figma"
cask "font-jetbrains-mono"
cask "github"
cask "google-backup-and-sync"
cask "grammarly"
cask "haptickey"
cask "iterm2"
cask "jetbrains-space"
cask "jetbrains-toolbox"
cask "jupyter-notebook-viewer"
cask "keka"
cask "keyboardcleantool"
cask "lunar"
cask "mactex"
cask "meetingbar"
cask "miniconda"
cask "mmhmm"
cask "notion"
cask "nvidia-geforce-now"
cask "obinskit"
cask "obs"
cask "openinterminal"
cask "openvpn-connect"
cask "opera"
cask "paw"
cask "pock"
cask "protonvpn"
cask "quitter"
cask "raspberry-pi-imager"
cask "spotify"
cask "syncthing"
cask "teamviewer"
cask "tor-browser"
cask "transmission"
cask "tunnelbear"
cask "turbo-boost-switcher"
cask "virtualbox"
cask "vlc"
cask "zoom"
cask "zoomus"
mas "1440", id: 1483764819
mas "1Password 7", id: 1333542190
mas "AdGuard for Safari", id: 1440147259
mas "Amphetamine", id: 937984704
mas "Craft", id: 1487937127
mas "Fantastical", id: 975937182
mas "Flycut", id: 442160987
mas "GarageBand", id: 682658836
mas "Grammarly for Safari", id: 1462114288
mas "Hush", id: 1544743900
mas "iMovie", id: 408981434
mas "Instapaper", id: 288545208
mas "Instapaper Save", id: 1481302432
mas "KeyKey", id: 1035137927
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "MindNode", id: 1289197285
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Reeder", id: 1449412482
mas "Shazam", id: 897118787
mas "Spark", id: 1176895641
mas "Studies", id: 1071676469
mas "Telegram", id: 747648890
mas "Termius", id: 1176074088
mas "Tweetbot", id: 1384080005
mas "Wayback Machine", id: 1472432422
